const cityTimezoneMap = {
    Seattle: "America/Los_Angeles",
    Phoenix: "America/Phoenix",
    Denver: "America/Denver",
    Chicago: "America/Chicago",
    Atlanta: "America/New_York",
    NewYork: "America/New_York",
    London: "Europe/London",
    Dubai: "Asia/Dubai",
    Tokyo: "Asia/Tokyo",
    Sydney: "Australia/Sydney",
    Paris: "Europe/Paris",
    Berlin: "Europe/Berlin",
    Toronto: "America/Toronto",
    Vancouver: "America/Vancouver",
    LosAngeles: "America/Los_Angeles",
    HongKong: "Asia/Hong_Kong",
    Moscow: "Europe/Moscow",
    CapeTown: "Africa/Johannesburg",
    BuenosAires: "America/Argentina/Buenos_Aires",
    SãoPaulo: "America/Sao_Paulo",
    MexicoCity: "America/Mexico_City",
    Riyadh: "Asia/Riyadh",
    Beijing: "Asia/Shanghai",
    Singapore: "Asia/Singapore",
    Kolkata: "Asia/Kolkata",
    Seoul: "Asia/Seoul",
    Manila: "Asia/Manila",
    Jakarta: "Asia/Jakarta",
    Rome: "Europe/Rome",
    Madrid: "Europe/Madrid",
    Lisbon: "Europe/Lisbon",
    Athens: "Europe/Athens",
    Stockholm: "Europe/Stockholm",
    Nairobi: "Africa/Nairobi",
    Lagos: "Africa/Lagos",
    Cairo: "Africa/Cairo",
    Accra: "Africa/Accra",
    Bogotá: "America/Bogota",
    Lima: "America/Lima",
    Caracas: "America/Caracas",
    Quito: "America/Guayaquil",
    Auckland: "Pacific/Auckland",
    Wellington: "Pacific/Wellington",
    Fiji: "Pacific/Fiji",
    Anchorage: "America/Anchorage",
    NewDelhi: "Asia/Kolkata"
  };
  
  
  export default cityTimezoneMap;
  